In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
smart_glasses=pd.read_csv("data/glasses.csv")
smart_watch=pd.read_csv("data/F_smart_watch.csv")
smart_phone=pd.read_csv("data/F_smart_phone.csv")
report_df = pd.read_csv("data/final_report.csv")

In [3]:
smart_phone.head()

,timestamp,battery,light,pressure,proximity,step_counter,step_detector,ACC_X,ACC_Y,ACC_Z,...,ORI_Z,AUDIO_W,AUDIO_X,AUDIO_Y,AUDIO_Z,ROTATION_VECTOR_A,ROTATION_VECTOR_B,ROTATION_VECTOR_C,ROTATION_VECTOR_D,ROTATION_VECTOR_E
0,2017-06-29 07:45:16.506,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-06-29 07:45:16.514,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-06-29 07:45:16.579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-06-29 07:45:17.407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,32767.0,NaN,NaN,NaN,NaN,NaN
4,2017-06-29 07:45:18.407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,227.0,113.5,227.0,227.0,NaN,NaN,NaN,NaN,NaN

# Renaming the columns

In [4]:
smart_phone_columns_dict = {col:'Phone_'+col for col in smart_phone.columns if col!='timestamp'}
smart_phone_columns_dict

{'battery': 'Phone_battery',
 'light': 'Phone_light',
 'pressure': 'Phone_pressure',
 'proximity': 'Phone_proximity',
 'step_counter': 'Phone_step_counter',
 'step_detector': 'Phone_step_detector',
 'ACC_X': 'Phone_ACC_X',
 'ACC_Y': 'Phone_ACC_Y',
 'ACC_Z': 'Phone_ACC_Z',
 'GRAVITY_X': 'Phone_GRAVITY_X',
 'GRAVITY_Y': 'Phone_GRAVITY_Y',
 'GRAVITY_Z': 'Phone_GRAVITY_Z',
 'GYRO_X': 'Phone_GYRO_X',
 'GYRO_Y': 'Phone_GYRO_Y',
 'GYRO_Z': 'Phone_GYRO_Z',
 'LA_X': 'Phone_LA_X',
 'LA_Y': 'Phone_LA_Y',
 'LA_Z': 'Phone_LA_Z',
 'MAG_X': 'Phone_MAG_X',
 'MAG_Y': 'Phone_MAG_Y',
 'MAG_Z': 'Phone_MAG_Z',
 'ORI_X': 'Phone_ORI_X',
 'ORI_Y': 'Phone_ORI_Y',
 'ORI_Z': 'Phone_ORI_Z',
 'AUDIO_W': 'Phone_AUDIO_W',
 'AUDIO_X': 'Phone_AUDIO_X',
 'AUDIO_Y': 'Phone_AUDIO_Y',
 'AUDIO_Z': 'Phone_AUDIO_Z',
 'ROTATION_VECTOR_A': 'Phone_ROTATION_VECTOR_A',
 'ROTATION_VECTOR_B': 'Phone_ROTATION_VECTOR_B',
 'ROTATION_VECTOR_C': 'Phone_ROTATION_VECTOR_C',
 'ROTATION_VECTOR_D': 'Phone_ROTATION_VECTOR_D',
 'ROTATION_VECTOR_E': 'Phone_ROTATION_VECTOR_E'}

In [5]:
smart_phone.rename(columns=smart_phone_columns_dict, inplace=True)

In [6]:
smart_phone.head()

,timestamp,Phone_battery,Phone_light,Phone_pressure,Phone_proximity,Phone_step_counter,Phone_step_detector,Phone_ACC_X,Phone_ACC_Y,Phone_ACC_Z,...,Phone_ORI_Z,Phone_AUDIO_W,Phone_AUDIO_X,Phone_AUDIO_Y,Phone_AUDIO_Z,Phone_ROTATION_VECTOR_A,Phone_ROTATION_VECTOR_B,Phone_ROTATION_VECTOR_C,Phone_ROTATION_VECTOR_D,Phone_ROTATION_VECTOR_E
0,2017-06-29 07:45:16.506,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-06-29 07:45:16.514,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-06-29 07:45:16.579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-06-29 07:45:17.407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,32767.0,NaN,NaN,NaN,NaN,NaN
4,2017-06-29 07:45:18.407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,227.0,113.5,227.0,227.0,NaN,NaN,NaN,NaN,NaN

In [7]:
smart_watch.head()

,timestamp,battery,pressure,step_counter,step_detector,HEART_RATE_X,HEART_RATE_Y,ACC_X,ACC_Y,ACC_Z,...,MAG_Y,MAG_Z,ORI_X,ORI_Y,ORI_Z,ROTATION_VECTOR_A,ROTATION_VECTOR_B,ROTATION_VECTOR_C,ROTATION_VECTOR_D,ROTATION_VECTOR_E
0,2017-06-29 07:45:56.262,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-06-29 07:46:01.263,NaN,NaN,NaN,NaN,NaN,NaN,-0.344086,0.683304,9.967361,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-06-29 07:46:01.324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-06-29 07:46:01.329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-06-29 07:46:01.402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
smart_watch_columns_dict = {col:'Watch_'+col for col in smart_watch.columns if col!='timestamp'}
smart_watch_columns_dict

{'battery': 'Watch_battery',
 'pressure': 'Watch_pressure',
 'step_counter': 'Watch_step_counter',
 'step_detector': 'Watch_step_detector',
 'HEART_RATE_X': 'Watch_HEART_RATE_X',
 'HEART_RATE_Y': 'Watch_HEART_RATE_Y',
 'ACC_X': 'Watch_ACC_X',
 'ACC_Y': 'Watch_ACC_Y',
 'ACC_Z': 'Watch_ACC_Z',
 'GRAVITY_X': 'Watch_GRAVITY_X',
 'GRAVITY_Y': 'Watch_GRAVITY_Y',
 'GRAVITY_Z': 'Watch_GRAVITY_Z',
 'GYRO_X': 'Watch_GYRO_X',
 'GYRO_Y': 'Watch_GYRO_Y',
 'GYRO_Z': 'Watch_GYRO_Z',
 'LA_X': 'Watch_LA_X',
 'LA_Y': 'Watch_LA_Y',
 'LA_Z': 'Watch_LA_Z',
 'MAG_X': 'Watch_MAG_X',
 'MAG_Y': 'Watch_MAG_Y',
 'MAG_Z': 'Watch_MAG_Z',
 'ORI_X': 'Watch_ORI_X',
 'ORI_Y': 'Watch_ORI_Y',
 'ORI_Z': 'Watch_ORI_Z',
 'ROTATION_VECTOR_A': 'Watch_ROTATION_VECTOR_A',
 'ROTATION_VECTOR_B': 'Watch_ROTATION_VECTOR_B',
 'ROTATION_VECTOR_C': 'Watch_ROTATION_VECTOR_C',
 'ROTATION_VECTOR_D': 'Watch_ROTATION_VECTOR_D',
 'ROTATION_VECTOR_E': 'Watch_ROTATION_VECTOR_E'}

In [9]:
smart_watch.rename(columns=smart_watch_columns_dict, inplace=True)

In [10]:
smart_watch.columns

Index(['timestamp', 'Watch_battery', 'Watch_pressure', 'Watch_step_counter',
       'Watch_step_detector', 'Watch_HEART_RATE_X', 'Watch_HEART_RATE_Y',
       'Watch_ACC_X', 'Watch_ACC_Y', 'Watch_ACC_Z', 'Watch_GRAVITY_X',
       'Watch_GRAVITY_Y', 'Watch_GRAVITY_Z', 'Watch_GYRO_X', 'Watch_GYRO_Y',
       'Watch_GYRO_Z', 'Watch_LA_X', 'Watch_LA_Y', 'Watch_LA_Z', 'Watch_MAG_X',
       'Watch_MAG_Y', 'Watch_MAG_Z', 'Watch_ORI_X', 'Watch_ORI_Y',
       'Watch_ORI_Z', 'Watch_ROTATION_VECTOR_A', 'Watch_ROTATION_VECTOR_B',
       'Watch_ROTATION_VECTOR_C', 'Watch_ROTATION_VECTOR_D',
       'Watch_ROTATION_VECTOR_E'],
      dtype='object')

In [11]:
smart_glasses.columns

Index(['NUM', 'DATE', 'ACC_X', 'ACC_Y', 'ACC_Z', 'GYRO_X', 'GYRO_Y', 'GYRO_Z',
       'EOG_L', 'EOG_R', 'EOG_H', 'EOG_V'],
      dtype='object')

In [12]:
smart_glasses.head()

,NUM,DATE,ACC_X,ACC_Y,ACC_Z,GYRO_X,GYRO_Y,GYRO_Z,EOG_L,EOG_R,EOG_H,EOG_V
0,1,2017/06/29 08:00:00.406,-3242,10396,-6489,9117,2018,-819,-330,-186,-144,258
1,3,2017/06/29 08:00:00.426,-4014,11348,-15131,3359,-882,-2009,-305,-156,-149,230
2,5,2017/06/29 08:00:00.446,-3223,10918,-8496,-460,211,-2631,-64,84,-148,-10
3,7,2017/06/29 08:00:00.466,-5255,10690,-10854,1152,333,-3799,314,432,-118,-373
4,9,2017/06/29 08:00:00.486,-560,14164,-8619,-327,488,-2833,577,643,-66,-610

In [13]:
smart_glasses.drop(columns=['NUM'], inplace=True)

In [14]:
smart_glasses.rename(columns={"DATE":"timestamp"}, inplace=True)

In [15]:
smart_glasses_columns_dict = {col:'Glass_'+col for col in smart_glasses.columns if col!='timestamp'}
smart_glasses_columns_dict

{'ACC_X': 'Glass_ACC_X',
 'ACC_Y': 'Glass_ACC_Y',
 'ACC_Z': 'Glass_ACC_Z',
 'GYRO_X': 'Glass_GYRO_X',
 'GYRO_Y': 'Glass_GYRO_Y',
 'GYRO_Z': 'Glass_GYRO_Z',
 'EOG_L': 'Glass_EOG_L',
 'EOG_R': 'Glass_EOG_R',
 'EOG_H': 'Glass_EOG_H',
 'EOG_V': 'Glass_EOG_V'}

In [16]:
smart_glasses.rename(columns=smart_glasses_columns_dict, inplace=True)
smart_glasses.columns

Index(['timestamp', 'Glass_ACC_X', 'Glass_ACC_Y', 'Glass_ACC_Z',
       'Glass_GYRO_X', 'Glass_GYRO_Y', 'Glass_GYRO_Z', 'Glass_EOG_L',
       'Glass_EOG_R', 'Glass_EOG_H', 'Glass_EOG_V'],
      dtype='object')

# Rounding the timestamp into seconds, Group wrt timestamp & extract mean value of the features

In [17]:
smart_watch.timestamp = pd.to_datetime(smart_watch.timestamp)
smart_phone.timestamp = pd.to_datetime(smart_phone.timestamp)
smart_glasses.timestamp = pd.to_datetime(smart_glasses.timestamp)

In [18]:
smart_watch['timestamp']=smart_watch['timestamp'].dt.round('1s')
smart_phone['timestamp']=smart_phone['timestamp'].dt.round('1s')
smart_glasses['timestamp']=smart_glasses['timestamp'].dt.round('1s')

In [19]:
print("smart_watch shape : ",smart_watch.shape)
print("smart_phone shape : ",smart_phone.shape)
print("smart_glasses shape : ",smart_glasses.shape)

smart_watch shape :  (173662, 30)
smart_phone shape :  (1522407, 34)
smart_glasses shape :  (3975266, 11)

In [20]:
smart_watch.groupby("timestamp").mean()

,Watch_battery,Watch_pressure,Watch_step_counter,Watch_step_detector,Watch_HEART_RATE_X,Watch_HEART_RATE_Y,Watch_ACC_X,Watch_ACC_Y,Watch_ACC_Z,Watch_GRAVITY_X,...,Watch_MAG_Y,Watch_MAG_Z,Watch_ORI_X,Watch_ORI_Y,Watch_ORI_Z,Watch_ROTATION_VECTOR_A,Watch_ROTATION_VECTOR_B,Watch_ROTATION_VECTOR_C,Watch_ROTATION_VECTOR_D,Watch_ROTATION_VECTOR_E
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-06-29 07:45:56,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:01,NaN,969.3651,NaN,NaN,NaN,NaN,-0.344086,0.683304,9.967361,-0.341318,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.888610,-44.90509,31.284261,-3.337645,2.033706,0.036942,0.007465,-0.256608,0.965781,0.174533
2017-06-29 07:46:06,NaN,969.0265,NaN,NaN,173.000000,0.000000,-0.441055,0.788651,9.872787,-0.493833,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-06-29 07:46:07,NaN,NaN,NaN,NaN,172.000000,1.000000,NaN,NaN,NaN,NaN,...,24.205017,-46.57135,31.151400,-4.101418,2.917161,0.041041,0.014525,-0.265925,0.963010,0.174533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-13 20:21:32,NaN,NaN,NaN,NaN,58.871795,1.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:33,NaN,NaN,NaN,NaN,64.358491,1.018868,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:34,NaN,NaN,NaN,NaN,56.250000,0.833333,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:35,NaN,NaN,NaN,NaN,54.574468,1.042553,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-13 20:21:36,NaN,989.3108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
smart_watch = smart_watch.groupby("timestamp").mean()
smart_glasses = smart_glasses.groupby("timestamp").mean()
smart_phone = smart_phone.groupby("timestamp").mean()

In [22]:
smart_glasses.reset_index(inplace=True)
smart_watch.reset_index(inplace=True)
smart_phone.reset_index(inplace=True)

In [23]:
print("smart_watch shape : ",smart_watch.shape)
print("smart_phone shape : ",smart_phone.shape)
print("smart_glasses shape : ",smart_glasses.shape)

smart_watch shape :  (64591, 30)
smart_phone shape :  (501312, 34)
smart_glasses shape :  (80532, 11)

In [24]:
features_df = pd.merge(smart_watch, smart_glasses, on='timestamp', how='outer')
features_df = pd.merge(features_df, smart_phone, on='timestamp', how='outer')

In [25]:
features_df.shape

(559298, 73)

In [26]:
features_df.columns

Index(['timestamp', 'Watch_battery', 'Watch_pressure', 'Watch_step_counter',
       'Watch_step_detector', 'Watch_HEART_RATE_X', 'Watch_HEART_RATE_Y',
       'Watch_ACC_X', 'Watch_ACC_Y', 'Watch_ACC_Z', 'Watch_GRAVITY_X',
       'Watch_GRAVITY_Y', 'Watch_GRAVITY_Z', 'Watch_GYRO_X', 'Watch_GYRO_Y',
       'Watch_GYRO_Z', 'Watch_LA_X', 'Watch_LA_Y', 'Watch_LA_Z', 'Watch_MAG_X',
       'Watch_MAG_Y', 'Watch_MAG_Z', 'Watch_ORI_X', 'Watch_ORI_Y',
       'Watch_ORI_Z', 'Watch_ROTATION_VECTOR_A', 'Watch_ROTATION_VECTOR_B',
       'Watch_ROTATION_VECTOR_C', 'Watch_ROTATION_VECTOR_D',
       'Watch_ROTATION_VECTOR_E', 'Glass_ACC_X', 'Glass_ACC_Y', 'Glass_ACC_Z',
       'Glass_GYRO_X', 'Glass_GYRO_Y', 'Glass_GYRO_Z', 'Glass_EOG_L',
       'Glass_EOG_R', 'Glass_EOG_H', 'Glass_EOG_V', 'Phone_battery',
       'Phone_light', 'Phone_pressure', 'Phone_proximity',
       'Phone_step_counter', 'Phone_step_detector', 'Phone_ACC_X',
       'Phone_ACC_Y', 'Phone_ACC_Z', 'Phone_GRAVITY_X', 'Phone_GRAVITY_Y',
       'Phone_GRAVITY_Z', 'Phone_GYRO_X', 'Phone_GYRO_Y', 'Phone_GYRO_Z',
       'Phone_LA_X', 'Phone_LA_Y', 'Phone_LA_Z', 'Phone_MAG_X', 'Phone_MAG_Y',
       'Phone_MAG_Z', 'Phone_ORI_X', 'Phone_ORI_Y', 'Phone_ORI_Z',
       'Phone_AUDIO_W', 'Phone_AUDIO_X', 'Phone_AUDIO_Y', 'Phone_AUDIO_Z',
       'Phone_ROTATION_VECTOR_A', 'Phone_ROTATION_VECTOR_B',
       'Phone_ROTATION_VECTOR_C', 'Phone_ROTATION_VECTOR_D',
       'Phone_ROTATION_VECTOR_E'],
      dtype='object')

In [27]:
features_df.to_csv("data/features_combined.csv", index=None)

In [28]:
# Merging the features with labels

In [29]:
report_df = pd.read_csv("final_report.csv")
report_df

,Unnamed: 0,FROM,TO,activity,DURATION
0,0,2017-06-29 09:57:00,2017-06-29 10:17:00,Eat,20:00
1,2,2017-06-29 10:46:00,2017-06-29 11:07:00,In vehicle,21:00
2,4,2017-06-29 11:09:00,2017-06-29 12:12:00,Walk,03:00
3,5,2017-06-29 12:12:00,2017-06-29 12:21:00,Shop/Walk,09:00
4,6,2017-06-29 12:21:00,2017-06-29 12:29:00,Took off glasses/Shop/Walk,08:00
...,...,...,...,...,...
168,257,2017-07-12 16:40:00,2017-07-12 16:55:00,Walk,15:00
169,259,2017-07-12 17:00:00,2017-07-12 18:21:00,Meeting,21:00
170,261,2017-07-12 18:22:00,2017-07-12 18:27:00,In vehicle,05:00
171,263,2017-07-12 18:39:00,2017-07-12 19:10:00,In bus,31:00
172,265,2017-07-12 21:09:00,2017-07-12 21:51:00,Video games,42:00

In [30]:
report_df['FROM'] = pd.to_datetime(report_df['FROM'])
report_df['TO'] = pd.to_datetime(report_df['TO'])

In [31]:
# Create an empty DataFrame to store the expanded data
expanded_df = pd.DataFrame(columns=['timestamp', 'activity'])

# Iterate through each row in 'report_df' and expand the data for each second
for _, row in report_df.iterrows():
    from_time = row['FROM']
    to_time = row['TO']
    activity = row['activity']
    
    # Create a DatetimeIndex with 1-second frequency
    time_index = pd.date_range(from_time, to_time, freq='S')
    
    # Create a DataFrame with the expanded data for this row
    data = pd.DataFrame({'timestamp': time_index, 'activity': activity})
    
    # Append the data to the expanded DataFrame
    expanded_df = expanded_df.append(data)

# Reset the index of the expanded DataFrame
expanded_df.reset_index(drop=True, inplace=True)

# Print the resulting DataFrame
print(expanded_df)

/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)

/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)

                 timestamp     activity
0      2017-06-29 09:57:00          Eat
1      2017-06-29 09:57:01          Eat
2      2017-06-29 09:57:02          Eat
3      2017-06-29 09:57:03          Eat
4      2017-06-29 09:57:04          Eat
...                    ...          ...
453108 2017-07-12 21:50:56  Video games
453109 2017-07-12 21:50:57  Video games
453110 2017-07-12 21:50:58  Video games
453111 2017-07-12 21:50:59  Video games
453112 2017-07-12 21:51:00  Video games

[453113 rows x 2 columns]

/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)
/tmp/ipykernel_16842/188552681.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  expanded_df = expanded_df.append(data)

In [32]:
expanded_df.activity.value_counts()

At home                                             138867
Walking&party                                        34502
In computer                                          27610
Walk                                                 23789
In bus                                               21199
Pause                                                20524
Meeting                                              19385
Picnic                                               18601
Sleep                                                16261
Video games/At home                                  15544
Movie                                                12423
Train                                                11349
In vehicle                                           10028
In computer/Work                                      9722
Football                                              9301
In computer/At home                                   9066
Eat                                                   8709
Cooking                                               7264
Watching TV/At home                                   6602
Shopping& wearing                                     6181
Work                                                  4083
Video games                                           3782
Phone was out of the pocket (forgot)/At home          2942
Eat/At home                                           2524
In computer/Eat                                       2101
Running/At home                                       1741
Shop                                                  1562
Running                                               1261
Shop/Walk                                             1202
Eat/Phone was out of the pocket (forgot)/At home      1201
On bus stop/Walk                                      1021
Eat/In computer                                        901
Eat/Watching TV/At home                                601
At home/Eat                                            541
Took off glasses/Shop/Walk                             481
Walk/At home                                           181
On bus stop                                             61
Name: activity, dtype: int64

In [33]:
report_df = expanded_df
report_df.head()

            timestamp activity
0 2017-06-29 09:57:00      Eat
1 2017-06-29 09:57:01      Eat
2 2017-06-29 09:57:02      Eat
3 2017-06-29 09:57:03      Eat
4 2017-06-29 09:57:04      Eat

In [34]:
final_df = features_df.merge(report_df, on="timestamp", how="inner")

In [35]:
final_df.shape

(290656, 74)

In [41]:
final_df.to_csv("data/combined_sensor_data_with_features.csv", index=None)